Member.create!([
  {name: "Tony Hobkirk", title: "President", image: "small-tony.jpg", image_big: "medium-tony.jpg"},
  {name: "Josh Evey", title: "Vice President", image: "small-josh.jpg", image_big: "medium-josh.jph"},
  {name: "Jennifer Kauppi", title: "Secretary", image: "small-jennifer.jpg", image_big: "medium-jennifer.jpg"},
  {name: "Scott Houser", title: "Board Member", image: "small-scott.jpg", image_big: "medium-scott.jpg"},
  {name: "Rob Cruickshank", title: "Board Member", image: "small-rob.jpg", image_big: nil},
  {name: "Deb Cherachanko", title: "Board Member", image: "small-deb.jpg", image_big: nil},
  {name: "Ethan Jewett", title: "Board Member", image: "small-ethan.jpg", image_big: nil}
])
Post.create!([
  {title: "Pacific Northwest Search and Rescue is now accepting applications for 2015", author: "Scott Hillson", body: "PNWSAR is now accepting applications for our 2015 trainee class. Please click the 'join us' link above to find out more. Interviews will take place in the fall of 2014, and training will begin in January of 2015.", active: false},
  {title: "Save the date for Northwest SARCON 2014!", author: "Scott Hillson", body: "Dates have been announced for the 2014 edition of the Northwest Search and Rescue Conference, hosted by the Clackamas County Sherrif's office. The conference returns to Camp Kuratli at Trestle Glen in Boring Oregon September 26th through the 28th. Registration and information about the 2014 conference is available at http://www.co.clackamas.or.us/sheriff/sarcon/", active: false},
  {title: "PNWSAR is currently accepting applications for 2016", author: "Scott Hillson", body: "PNWSAR is now accepting applications for our Prospect class of 2016.  If you are interested in applying, please click on the Join Us link above.", active: false},
  {title: "SARCon 2015", author: "Scott Hillson", body: "Please join us at NW SARCon 2015, presented by the Clackamas County Sheriff's Office. The conference returns September 25-27 to Camp Kuratli at Trestle Glen in Boring, Oregon. For more details: \r\nhttp://www.clackamas.us/sheriff/sarcon/", active: false}
])
Search.create!([
  {title: "Gales Creek Missing Male", author: "Scott Houser", body: "On 4/22 the Washington County Sherriff's Office requested assistance from PNWSAR in the search for a 51 year old missing Hillsboro man near the Gales Creek Campground in western Washington County.  The man had been previously reported by relatives as missing and possibly despondent.  His vehicle was located abandoned near the campground.\r\n\r\nFor three days combined search teams from several counties launched a large search effort in the area around the campground and many nearby trails, mountains and drainages.  On the first day PNWSAR was responsible for searching a 300 meter radius around the location of the man's vehicle.  On the second and third day PNWSAR was assigned to search several very steep and difficult areas between Gales Creek and Story Burn Road, and were assisted by members of Yamhill County SAR and the Washington County Explorers.  Several storm fronts brought heavy rain and made search conditions challenging.  PNWSAR completed all requested assignments but found no clues or signs of the missing man.\r\n\r\nOn 4/24 WCSO deputies made the difficult decision to suspend the search.  PNWSAR extends our gratitude to our fellow SAR volunteers and our sympathy to the missing man's friends and family.", search_date: "2014-04-22", active: nil},
  {title: "Horsetail Falls", author: "Scott Houser", body: "On 7/10, the Multnomah County Sheriff's Office (MCSO) requested assistance from PNWSAR in the search for a missing woman above Horsetail Falls in the Columbia River Gorge.  A PNWSAR team deployed on the Tanner Creek Trail above Wahclella Falls and began searching for the woman.  At approximately 07:00, the woman was spotted by a search aircraft and later escorted back to base by a MCSO SAR team.  Communications and logistics support was provided by Mountain Wave Communications.", search_date: "2014-07-10", active: nil},
  {title: "Trillium Lake Lost Family", author: "Scott Houser", body: "On 01/24, the Clackamas County Sherriff’s Office (CCSO) requested assistance from PNWSAR in the rescue of a family who became lost while hiking near Trillium Lake.  The family called 911 and requested assistance after becoming lost when darkness fell.  Using cell phone tracking, a PNWSAR team located all five members of the family, including a two year old child, and began escorting them back to the parking lot.  A second PNWSAR team joined after approximately one mile, and determined that one family member was having trouble walking and requested transport.  The subject was treated and transported the remaining distance.  All family members reunited at base and reported no serious injuries.  Communications and cell phone tracking provided by Mountain Wave Emergency Communications.", search_date: "2015-01-24", active: nil},
  {title: "Goat Mountain Recovery", author: "Scott Houser", body: "On 01/22, the Clackamas County Sherriff’s Office (CCSO) requested assistance from PNWSAR in the recovery of the body of a man who had fallen off Goat Mountain near Clear Lake.  A PNWSAR team responded and deployed a rope system to lower the subject approximately 200 meters to an appropriate location for transport.  PNWSAR extends our condolences to the subject's friends and family.  Transport and communications provided by Mountain Wave Emergency Communications.", search_date: "2015-01-22", active: nil},
  {title: "Missing Hiker Salmon River Trail", author: "Scott Houser", body: "On 01/20, the Clackamas County Sherriff’s Office (CCSO) requested assistance from PNWSAR in the search for a missing hiker on the Salmon River Trail.  The subject had been reported overdue.  A PNWSAR hasty team deployed early in the morning and swept the trail to the Salmon/Kinzel junction.  Around noon, while the hasty team was planning the next portion of the search, the team located the subject as she was coming back down the trail after having spent an unplanned night in the woods.  She was treated and escorted back to the trailhead.  Communications provided by Mountain Wave Emergency Communications.", search_date: "2015-01-20", active: nil},
  {title: "Lost Climber Paradise Park", author: "Scott Houser", body: "On 01/10, the Clackamas County Sherriff’s Office (CCSO) requested assistance from PNWSAR in the search for a missing climber in the Paradise Park area of Mt. Hood.  PNWSAR team members responded and formed two teams to monitor trailheads on the lower portion of the mountain.  Portland Mountain Rescue and the Timberline Ski Patrol each deployed a team to search the upper portion of the mountain near the climbers last known location. At approximately 02:30 the Ski Patrol located the subject and guided him back to Timberline Lodge. Communications and cell phone tracking were provided by Mountain Wave Emergency Communications.", search_date: "2015-01-10", active: nil},
  {title: "Bagby Hot Springs Packout", author: "Scott Houser", body: "On 01/18, the Clackamas County Sherriff’s Office (CCSO) requested assistance from PNWSAR with the transport of a woman described as unresponsive at Bagby Hot Springs.  Team members arrived at approximately 23:00 hours to find the subject being treated by medics from the AMR Reach and Treat (RAT) team.  The subject was in an unresponsive but non-life threatening condition.  PNWSAR members packaged the subject in a wheeled litter and transported her to the trailhead where she was transferred to a waiting ambulance.  Communications provided by Mountain Wave Emergency", search_date: "2015-01-18", active: nil},
  {title: "Wahkeena Falls Injured Hiker", author: "Scott Houser", body: "On 12/14 the Multnomah County Sheriff's Office (MCSO) requested support from PNWSAR in the packout of an injured hiker above Wahkeena Falls in the Columbia Gorge.  The subject had been injured and was being taken by litter down the Wahkeena Falls trail by Corbett Fire and AMR RAT team members.\r\n\r\nPNWSAR members arrived at dusk and proceeded up the trail where they encountered the subject and litter. Rescuers slowly descended the trail several miles down multiple switchbacks in challenging conditions to the trailhead and finally transferred the subject to an ambulance at 8 p.m.", search_date: "2014-12-14", active: nil},
  {title: "Lost Female Timothy Lake", author: "Scott Houser", body: "On 03/11, PNWSAR was asked to assist with the search for a lost female near Timothy Lake.  Just as PNW was preparing to enter the field, the subject was located by  search aircraft and escorted to Base by a team from Portland Mountain Rescue.  ", search_date: "2015-03-11", active: nil},
  {title: "Bonneville Dam Packout", author: "Scott Houser", body: "On 04/18, PNWSAR was asked by the Multnomah County Sheriff's Office to assist with the packout of a female hiker near Bonneville Dam.  A team from PNW arrived on the scene and assisted with the last part of the operation.", search_date: "2015-04-18", active: nil},
  {title: "Hunchback Lost Male", author: "Scott Houser", body: "On 05/15 the Clackamas County Sheriff's Office requested assistance from PNWSAR in the search for a male hiker missing on Hunchback Mountain near ZigZig.  The man had been attending a nearby conference when he decided to go on a hike, got lost, and contacted 911.  A large team from PNW deployed at night and searched until dawn, when the subject was located.  He was assisted back to Base after reporting no injuries.   Communications provided by Mountain Wave.", search_date: "2015-05-15", active: nil},
  {title: "Babgby Hot Springs Packout", author: "Scott Houser", body: "On 05/09, the Clackamas County Sheriff's Office requested assistance from PNWSAR with the packout of a female from Bagby Hot Springs.  The subject was in a non-responsive but non-life threatening condition.   Along with a Reach and Treat (RAT) medical team from AMR, a PNW team packaged the subject and transported her to Base by litter, where she was transferred to an ambulance for observation.", search_date: "2015-05-09", active: nil},
  {title: "Mirror Lake Packout", author: "Scott Houser", body: "On 05/10, The Clackamas County Sheriff's Office requested assistance from PNWSAR with the packout of a female subject from Mirror Lake.  A PNW team arrived and hiked to the subject, who had suffered a broken leg and had been treated and then packaged in a litter by Hoodland Fire.  The combined PNW and HF team transported the subject to the Mirror Lake Trailhead, where she was transferred to an ambulance.", search_date: "2015-05-10", active: nil}
])
User.create!([
  {name: "Scott Hillson", email: "scott.hillson@gmail.com", token: "2aNOh4B5_9_S2zl-W87fdw", admin: true, password_digest: "$2a$10$1JNUZt3dCQOwe6Do9/f.mO6x96rTUkI9hMPed7Pa3L7kl2P/SOzHO", activated: false},
  {name: "Scott Houser", email: "scotthouser@live.com", token: "_aaWrP3KNTXeOQDo7rzoUA", admin: true, password_digest: "$2a$10$mnPbURry2zLU6TVCY/Ohdukg7HpFvOVSUdLjC..AEA1iGnga3.yCu", activated: false}
])
