class SeedThoseEqs < ActiveRecord::Migration
  def change
    add_column :equipment, :weight, :integer
    add_column :equipment, :sort, :integer
    add_column :equipment_categories, :sort, :integer
    Equipment.destroy_all
    Equipment.create!([
      {description: "", expiration: "", importance: "Required", notes: "", status: "", quantity: nil, created_by: 1, name: "pants or tights (no cotton)", examples: "http://www.backcountry.com/patagonia-capilene-lightweight-bottoms-mens", equipment_category_id: 2, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "running shoes", examples: nil, equipment_category_id: 2, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "athletic socks (no cotton)", examples: nil, equipment_category_id: 2, team_gear: nil},
      {description: "", expiration: "", importance: "Required", notes: "", status: "", quantity: 1, created_by: 1, name: "waterproof jacket and pants, weather appropriate as necessary", examples: "", equipment_category_id: 2, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "assignment nutrition", examples: nil, equipment_category_id: 3, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "headlamp, extra batteries or backup light", examples: nil, equipment_category_id: 3, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "fire starter", examples: nil, equipment_category_id: 3, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "knife", examples: nil, equipment_category_id: 3, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "map", examples: nil, equipment_category_id: 4, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "compass", examples: nil, equipment_category_id: 4, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "gps", examples: nil, equipment_category_id: 4, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "radio", examples: nil, equipment_category_id: 4, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "inreach", examples: nil, equipment_category_id: 4, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "orange shirt", examples: nil, equipment_category_id: 5, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "long pants", examples: nil, equipment_category_id: 5, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "base layer, top and bottom, weather appropriate", examples: nil, equipment_category_id: 5, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "sweater, wool or polyester", examples: nil, equipment_category_id: 5, team_gear: nil},
      {description: "", expiration: "", importance: "Required", notes: "", status: "", quantity: 1, created_by: 1, name: "gloves, weather appropriate", examples: "", equipment_category_id: 5, team_gear: nil},
      {description: "", expiration: "", importance: "Required", notes: "", status: "", quantity: 2, created_by: 1, name: "pair socks", examples: "", equipment_category_id: 5, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "hat/helmet liner/balaclava , weather appropriate", examples: nil, equipment_category_id: 5, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "leather work gloves", examples: nil, equipment_category_id: 5, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "waterproof breathable shell pants", examples: nil, equipment_category_id: 5, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "orange outer shell", examples: nil, equipment_category_id: 5, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "Boots with Lug Soles - Over Ankle; NO TENNIS SHOE TYPE BOOTS", examples: nil, equipment_category_id: 5, team_gear: nil},
      {description: nil, expiration: nil, importance: "Recommended", notes: nil, status: nil, quantity: 1, created_by: 1, name: "gaiters", examples: nil, equipment_category_id: 5, team_gear: nil},
      {description: nil, expiration: nil, importance: "Recommended", notes: nil, status: nil, quantity: 1, created_by: 1, name: "extra sweater", examples: nil, equipment_category_id: 5, team_gear: nil},
      {description: nil, expiration: nil, importance: "Recommended", notes: nil, status: nil, quantity: 1, created_by: 1, name: "extra base layer", examples: nil, equipment_category_id: 5, team_gear: nil},
      {description: nil, expiration: nil, importance: "Recommended", notes: nil, status: nil, quantity: 1, created_by: 1, name: "back support", examples: nil, equipment_category_id: 5, team_gear: nil},
      {description: "", expiration: "", importance: "Recommended", notes: "", status: "", quantity: 1, created_by: 1, name: "change of clothes and shoes for 2nd assignment or ride home", examples: "", equipment_category_id: 5, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "compass with sighting mirror and mechanical declination adjustment", examples: nil, equipment_category_id: 6, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "gps (garmin preferred)", examples: nil, equipment_category_id: 6, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "notepad (waterproof - Rite in the Rain)", examples: nil, equipment_category_id: 6, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "waterproof pen and permanent marker", examples: nil, equipment_category_id: 6, team_gear: nil},
      {description: nil, expiration: nil, importance: "Recommended", notes: nil, status: nil, quantity: 1, created_by: 1, name: "utm grid reader", examples: nil, equipment_category_id: 6, team_gear: nil},
      {description: nil, expiration: nil, importance: "Recommended", notes: nil, status: nil, quantity: 1, created_by: 1, name: "Maps - USGS 7.5 minute Topo - Usually provided by IC", examples: nil, equipment_category_id: 6, team_gear: nil},
      {description: nil, expiration: nil, importance: "Optional", notes: nil, status: nil, quantity: 1, created_by: 1, name: "map case", examples: nil, equipment_category_id: 6, team_gear: nil},
      {description: nil, expiration: nil, importance: "Optional", notes: nil, status: nil, quantity: 1, created_by: 1, name: "altimeter", examples: nil, equipment_category_id: 6, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "backpack - sufficient to hold all required items", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "knife - fixed blade (see knife policy)", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "Locking Carabiners - 2 ea. (3/4\" gate opening)", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "prusik - 6mm x 6'", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "purcell prusik - 6mm x 10'", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "signal mirror (may use compass mirror)", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "food and snacks (24 hr supply, 2000+ calories)", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "survival blanket (heavy duty 5x7 - no thin mylar)", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "eye protection (safety glasses, goggles, sunglasses)", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "survey tape (hot pink)", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "poly tarp - blue 8' x 10' or bivy sack", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "plastic whistle (fox 40 or storm, pea-less design)", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "spare flashlight w/ extra batteries and bulbs", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "fire starters (homemade recommended)", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "water, 2 quarts minimum", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "1\" tubular webbing - 14' (blue) and 20' (red) lengths", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "extra batteries for FRS/VHF radio, GPS, etc", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "550 nylon cord - 50' bright colors", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "toilet paper", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "REI or UCO Storm Proof Wooden Matches", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "wood saw", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "Match Holder (Plastic, Waterproof)", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "Ziploc Bags - 2 ea Gallon and 2 ea Quart (Freezer)", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "Climbing Helmet - UIAA/CE certified", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "Duct Tape - 3 ft min", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "Legal ID/SAR ID (provided by team)", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "Water Treatment (Chemical, Filter, UV, Boiling)", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "Headlamp or Hands-Free Light w/ extra batteries", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Recommended", notes: nil, status: nil, quantity: 1, created_by: 1, name: "green light sticks", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Recommended", notes: nil, status: nil, quantity: 1, created_by: 1, name: "frs/gmrs radio - pnwsar standard operating channel is 9-11", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Recommended", notes: nil, status: nil, quantity: 1, created_by: 1, name: "metal cup or small pot", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: "", expiration: "", importance: "Recommended", notes: "", status: "", quantity: 1, created_by: 1, name: "watch", examples: "", equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Recommended", notes: nil, status: nil, quantity: 1, created_by: 1, name: "adjustable pack cover", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Recommended", notes: nil, status: nil, quantity: 1, created_by: 1, name: "backpacking stove", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Recommended", notes: nil, status: nil, quantity: 1, created_by: 1, name: "camera", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Recommended", notes: nil, status: nil, quantity: 1, created_by: 1, name: "small foam pad", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Recommended", notes: nil, status: nil, quantity: 1, created_by: 1, name: "tent stakes", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Recommended", notes: nil, status: nil, quantity: 1, created_by: 1, name: "chest harness", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Optional", notes: nil, status: nil, quantity: 1, created_by: 1, name: "garbage bags (large)", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Optional", notes: nil, status: nil, quantity: 1, created_by: 1, name: "binoculars", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Optional", notes: nil, status: nil, quantity: 1, created_by: 1, name: "knife sharpener", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Optional", notes: nil, status: nil, quantity: 1, created_by: 1, name: "trekking poles", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Optional", notes: nil, status: nil, quantity: 1, created_by: 1, name: "handkerchief", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Optional", notes: nil, status: nil, quantity: 1, created_by: 1, name: "eating utensils", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Optional", notes: nil, status: nil, quantity: 1, created_by: 1, name: "aluminum foil (heavy duty)", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Optional", notes: nil, status: nil, quantity: 1, created_by: 1, name: "cigarette lighter", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Optional", notes: nil, status: nil, quantity: 1, created_by: 1, name: "knee pads", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Optional", notes: nil, status: nil, quantity: 1, created_by: 1, name: "toiletry/towels", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Optional", notes: nil, status: nil, quantity: 1, created_by: 1, name: "candle (long burning)", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Optional", notes: nil, status: nil, quantity: 1, created_by: 1, name: "tape measure", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Optional", notes: nil, status: nil, quantity: 1, created_by: 1, name: "tracking stick", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Optional", notes: nil, status: nil, quantity: 1, created_by: 1, name: "rope throw bag", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Optional", notes: nil, status: nil, quantity: 1, created_by: 1, name: "narrow-band vhf radio", examples: nil, equipment_category_id: 7, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "barrier protection gloves - 2 pair, no latex", examples: nil, equipment_category_id: 8, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "heat packs", examples: nil, equipment_category_id: 8, team_gear: nil},
      {description: "", expiration: "", importance: "Required", notes: "", status: "", quantity: 6, created_by: 1, name: "bandages 4x4", examples: "", equipment_category_id: 8, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "triangular bandage", examples: nil, equipment_category_id: 8, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 6, created_by: 1, name: "adhesive bandages 1\"", examples: nil, equipment_category_id: 8, team_gear: nil},
      {description: "", expiration: "", importance: "Required", notes: "", status: "", quantity: 1, created_by: 1, name: "personal medications", examples: "", equipment_category_id: 8, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "adhesive tape - cloth, 1\"", examples: nil, equipment_category_id: 8, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "waterproof soap note sheet", examples: nil, equipment_category_id: 8, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "cpr barrier protector", examples: nil, equipment_category_id: 8, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "ace wrap/israeli bandage", examples: nil, equipment_category_id: 8, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "compress - 5x9", examples: nil, equipment_category_id: 8, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "roll gauze (eg: kerlix) - 2\" min", examples: nil, equipment_category_id: 8, team_gear: nil},
      {description: nil, expiration: nil, importance: "Recommended", notes: nil, status: nil, quantity: 1, created_by: 1, name: "moleskin, blister block or equivalent", examples: nil, equipment_category_id: 8, team_gear: nil},
      {description: nil, expiration: nil, importance: "Recommended", notes: nil, status: nil, quantity: 1, created_by: 1, name: "lip protection", examples: nil, equipment_category_id: 8, team_gear: nil},
      {description: nil, expiration: nil, importance: "Recommended", notes: nil, status: nil, quantity: 1, created_by: 1, name: "sunscreen", examples: nil, equipment_category_id: 8, team_gear: nil},
      {description: nil, expiration: nil, importance: "Recommended", notes: nil, status: nil, quantity: 1, created_by: 1, name: "insect repellent", examples: nil, equipment_category_id: 8, team_gear: nil},
      {description: nil, expiration: nil, importance: "Recommended", notes: nil, status: nil, quantity: 1, created_by: 1, name: "scissors or trauma shears", examples: nil, equipment_category_id: 8, team_gear: nil},
      {description: nil, expiration: nil, importance: "Recommended", notes: nil, status: nil, quantity: 1, created_by: 1, name: "thermometer", examples: nil, equipment_category_id: 8, team_gear: nil},
      {description: nil, expiration: nil, importance: "Recommended", notes: nil, status: nil, quantity: 1, created_by: 1, name: "sam splint or wire splint", examples: nil, equipment_category_id: 8, team_gear: nil},
      {description: nil, expiration: nil, importance: "Recommended", notes: nil, status: nil, quantity: 1, created_by: 1, name: "super glue", examples: nil, equipment_category_id: 8, team_gear: nil},
      {description: nil, expiration: nil, importance: "Recommended", notes: nil, status: nil, quantity: 1, created_by: 1, name: "antihistamine", examples: nil, equipment_category_id: 8, team_gear: nil},
      {description: nil, expiration: nil, importance: "Recommended", notes: nil, status: nil, quantity: 1, created_by: 1, name: "cold packs", examples: nil, equipment_category_id: 8, team_gear: nil},
      {description: nil, expiration: nil, importance: "Recommended", notes: nil, status: nil, quantity: 1, created_by: 1, name: "electrolyte replacement", examples: nil, equipment_category_id: 8, team_gear: nil},
      {description: nil, expiration: nil, importance: "Recommended", notes: nil, status: nil, quantity: 1, created_by: 1, name: "first aid handbook", examples: nil, equipment_category_id: 8, team_gear: nil},
      {description: nil, expiration: nil, importance: "Recommended", notes: nil, status: nil, quantity: 1, created_by: 1, name: "analgesic (tylenol/aspirin/ibuprofin/naproxin sodium)", examples: nil, equipment_category_id: 8, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "national forest maps", examples: nil, equipment_category_id: 9, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "gazeteer/benchmark atlas", examples: nil, equipment_category_id: 9, team_gear: nil},
      {description: nil, expiration: nil, importance: "Recommended", notes: nil, status: nil, quantity: 1, created_by: 1, name: "large backpack", examples: nil, equipment_category_id: 9, team_gear: nil},
      {description: nil, expiration: nil, importance: "Recommended", notes: nil, status: nil, quantity: 1, created_by: 1, name: "tow strap", examples: nil, equipment_category_id: 9, team_gear: nil},
      {description: nil, expiration: nil, importance: "Recommended", notes: nil, status: nil, quantity: 1, created_by: 1, name: "wool blanket", examples: nil, equipment_category_id: 9, team_gear: nil},
      {description: nil, expiration: nil, importance: "Recommended", notes: nil, status: nil, quantity: 1, created_by: 1, name: "tire chains", examples: nil, equipment_category_id: 9, team_gear: nil},
      {description: nil, expiration: nil, importance: "Recommended", notes: nil, status: nil, quantity: 1, created_by: 1, name: "shovel", examples: nil, equipment_category_id: 9, team_gear: nil},
      {description: nil, expiration: nil, importance: "Recommended", notes: nil, status: nil, quantity: 1, created_by: 1, name: "sleeping bag", examples: nil, equipment_category_id: 9, team_gear: nil},
      {description: nil, expiration: nil, importance: "Recommended", notes: nil, status: nil, quantity: 1, created_by: 1, name: "backpacking tent", examples: nil, equipment_category_id: 9, team_gear: nil},
      {description: nil, expiration: nil, importance: "Recommended", notes: nil, status: nil, quantity: 1, created_by: 1, name: "snowshoes", examples: nil, equipment_category_id: 10, team_gear: nil},
      {description: nil, expiration: nil, importance: "Recommended", notes: nil, status: nil, quantity: 1, created_by: 1, name: "metal snow shovel, no plastic", examples: nil, equipment_category_id: 10, team_gear: nil},
      {description: nil, expiration: nil, importance: "Recommended", notes: nil, status: nil, quantity: 1, created_by: 1, name: "goggles", examples: nil, equipment_category_id: 10, team_gear: nil},
      {description: nil, expiration: nil, importance: "Recommended", notes: nil, status: nil, quantity: 1, created_by: 1, name: "avalanche beacon", examples: nil, equipment_category_id: 10, team_gear: nil},
      {description: nil, expiration: nil, importance: "Recommended", notes: nil, status: nil, quantity: 1, created_by: 1, name: "avalanche probe", examples: nil, equipment_category_id: 10, team_gear: nil},
      {description: nil, expiration: nil, importance: "Optional", notes: nil, status: nil, quantity: 1, created_by: 1, name: "snow saw", examples: nil, equipment_category_id: 10, team_gear: nil},
      {description: nil, expiration: nil, importance: "Optional", notes: nil, status: nil, quantity: 1, created_by: 1, name: "crampons", examples: nil, equipment_category_id: 10, team_gear: nil},
      {description: nil, expiration: nil, importance: "Optional", notes: nil, status: nil, quantity: 1, created_by: 1, name: "skis - xc/at", examples: nil, equipment_category_id: 10, team_gear: nil},
      {description: nil, expiration: nil, importance: "Optional", notes: nil, status: nil, quantity: 1, created_by: 1, name: "ice axe", examples: nil, equipment_category_id: 10, team_gear: nil},
      {description: nil, expiration: nil, importance: "Optional", notes: nil, status: nil, quantity: 1, created_by: 1, name: "ski poles", examples: nil, equipment_category_id: 10, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "seat harness (uiaa or nfpa approved)", examples: nil, equipment_category_id: 11, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "4+ locking carabiners (27+ kn mbs), unencumbered", examples: nil, equipment_category_id: 11, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "approved rappel device (scarab, atc guide, grigri or rescue 8 (with ears))", examples: nil, equipment_category_id: 11, team_gear: nil},
      {description: "", expiration: "", importance: "Required", notes: "", status: "", quantity: 1, created_by: 1, name: "one-handed knife, rescue hook, or emt shears", examples: "", equipment_category_id: 11, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "100’ of rope (see requirements)", examples: nil, equipment_category_id: 11, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "22+ kn pulley", examples: nil, equipment_category_id: 11, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "all terrain mountain bike", examples: nil, equipment_category_id: 12, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "offroad tires", examples: nil, equipment_category_id: 12, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "rear cargo rack or daypack", examples: nil, equipment_category_id: 12, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "bike light, 300 lumens or higher with enough batteries to last at least 6 hours", examples: nil, equipment_category_id: 12, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "red rear tail light or reflector ", examples: nil, equipment_category_id: 12, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "bicycle multi-tool", examples: nil, equipment_category_id: 13, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 2, created_by: 1, name: "tire levers or knowledge of how to use quick releases as levers ", examples: nil, equipment_category_id: 13, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "patch kit", examples: nil, equipment_category_id: 13, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 2, created_by: 1, name: "spare tubes", examples: nil, equipment_category_id: 13, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "tire pump", examples: nil, equipment_category_id: 13, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "chain tool", examples: nil, equipment_category_id: 13, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "spare chain links", examples: nil, equipment_category_id: 13, team_gear: nil},
      {description: nil, expiration: nil, importance: "Recommended", notes: nil, status: nil, quantity: 1, created_by: 1, name: "co2 inflator to supplement tire pump", examples: nil, equipment_category_id: 13, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "waterproof pants and jacket", examples: nil, equipment_category_id: 14, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "bicycle jersey or suitable long sleeve shirt (no cotton)", examples: nil, equipment_category_id: 14, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "light hiking boots or comfortable cycling shoes", examples: nil, equipment_category_id: 14, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "wool or comparable socks", examples: nil, equipment_category_id: 14, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "ansi approved cycling helmet", examples: nil, equipment_category_id: 14, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "shatter resistant glasses", examples: nil, equipment_category_id: 14, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "full finger bike gloves", examples: nil, equipment_category_id: 14, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "map", examples: nil, equipment_category_id: 15, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "compass and gps", examples: nil, equipment_category_id: 15, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "backup light", examples: nil, equipment_category_id: 15, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "extra food", examples: nil, equipment_category_id: 15, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "64+ ounces of water", examples: nil, equipment_category_id: 15, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "extra clothing, weather appropriate", examples: nil, equipment_category_id: 15, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "fire starter", examples: nil, equipment_category_id: 15, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "5x7 emergency blanket or bivy", examples: nil, equipment_category_id: 15, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "knife", examples: nil, equipment_category_id: 15, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "whistle", examples: nil, equipment_category_id: 15, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "pink flagging", examples: nil, equipment_category_id: 15, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "toilet paper", examples: nil, equipment_category_id: 15, team_gear: nil},
      {description: nil, expiration: nil, importance: "Required", notes: nil, status: nil, quantity: 1, created_by: 1, name: "vhf radio", examples: nil, equipment_category_id: 15, team_gear: nil}
    ])
    EquipmentCategory.destroy_all
    EquipmentCategory.create!([
      {category_name: "trt clothing", display_name: "Clothing", team_id: "46", created_by: 1, id: 2},
      {category_name: "trt general", display_name: "General", team_id: "46", created_by: 1, id: 3},
      {category_name: "trt team", display_name: "Team", team_id: "46", created_by: 1, id: 4},
      {category_name: "team clothing", display_name: "Clothing", team_id: "36", created_by: 1, id: 5},
      {category_name: "team navigation", display_name: "Navigation", team_id: "36", created_by: 1, id: 6},
      {category_name: "team general", display_name: "General", team_id: "36", created_by: 1, id: 7},
      {category_name: "team first aid", display_name: "First Aid Kit", team_id: "36", created_by: 1, id: 8},
      {category_name: "team vehicle", display_name: "In Your Vehicle", team_id: "36", created_by: 1, id: 9},
      {category_name: "team winter", display_name: "Winter Gear", team_id: "36", created_by: 1, id: 10},
      {category_name: "rst personal", display_name: "Personal Equipment", team_id: "41", created_by: 1, id: 11},
      {category_name: "mbt personal", display_name: "Personal Equipment", team_id: "35", created_by: 1, id: 12},
      {category_name: "mtb tools", display_name: "Repair Equipment", team_id: "35", created_by: 1, id: 13},
      {category_name: "mtb clothing", display_name: "Clothing", team_id: "35", created_by: 1, id: 14},
      {category_name: "mtb general", display_name: "General", team_id: "35", created_by: 1, id: 15}
    ])
    Group.destroy_all
    Group.create!([
      {name: "ATV", d4h_id: 4781},
      {name: "Board of Directors", d4h_id: 892},
      {name: "Call Group 0", d4h_id: 1815},
      {name: "Call Group 1", d4h_id: 1816},
      {name: "EMR", d4h_id: 948},
      {name: "EMS - EMT", d4h_id: 949},
      {name: "EMS - EMT-I", d4h_id: 950},
      {name: "EMS Committee", d4h_id: 935},
      {name: "EMS EMT-P", d4h_id: 4622},
      {name: "ITCs", d4h_id: 3707},
      {name: "Logistics", d4h_id: 3768},
      {name: "mbt", d4h_id: 894, id: 35},
      {name: "general", d4h_id: 1421, id: 36},
      {name: "PNW PICs", d4h_id: 987},
      {name: "PR Committee", d4h_id: 893},
      {name: "Prospects", d4h_id: 896},
      {name: "RN", d4h_id: 4246},
      {name: "rst", d4h_id: 895, id: 41},
      {name: "RST Committee", d4h_id: 6518},
      {name: "tracking", d4h_id: 4698},
      {name: "trainees", d4h_id: 904},
      {name: "Training Committee", d4h_id: 891},
      {name: "trt", d4h_id: 4595, id: 46}
    ])
  end
end
